# Product dimension with Snapshot CDC and SCD Type 2
# Append-only bronze table → Python function extracts snapshots by date → Snapshot CDC SCD Type 2
# Snapshots identified by extracting date from _source_file_path (e.g., "2024-01-08_product.csv")

pipeline: silver_dimensions_sap
flowgroup: product_dim_TMPL008

use_template: TMPL008_silver_snapshot_dimension_scd2_template
template_parameters:
  table_name: prd
  source_system: sap
  source_function:
    file: "py_functions/product_snapshot_func.py"
    function: "next_product_snapshot_and_version"
  primary_keys:
    - "product_id"
  type_casting:
    product_id: "BIGINT"
    sku: "STRING"
    upc: "STRING"
    name: "STRING"
    brand_id: "BIGINT"
    category_id: "BIGINT"
    uom_id: "BIGINT"
    open_food_facts_code: "STRING"
    quantity: "STRING"
    packaging: "STRING"
    nutrition_data: "STRING"
    base_cost: "DECIMAL(10,2)"
    base_price: "DECIMAL(10,2)"
    reorder_quantity: "BIGINT"
    shelf_life_days: "BIGINT"
    status: "STRING"
    created_at: "TIMESTAMP"
    updated_at: "TIMESTAMP"
    last_update_dttm: "TIMESTAMP"
    _processing_timestamp: "TIMESTAMP"
  track_history_except:
    - "_processing_timestamp"
    - "_source_file_path"
    - "_snapshot_date"
