columns:
  - "product_id: BIGINT"
  - "sku: STRING"
  - "upc: STRING"
  - "name: STRING"
  - "brand_id: BIGINT"
  - "category_id: BIGINT"
  - "uom_id: BIGINT"
  - "open_food_facts_code: STRING"
  - "quantity: STRING"
  - "packaging: STRING"
  - "nutrition_data: STRING"
  - "base_cost: DECIMAL(10,2)"
  - "base_price: DECIMAL(10,2)"
  - "reorder_quantity: BIGINT"
  - "shelf_life_days: BIGINT"
  - "status: STRING"
  - "created_at: TIMESTAMP"
  - "updated_at: TIMESTAMP"
  - "last_update_dttm: TIMESTAMP"
